"""
Recoup — Pydantic Schemas for Synthetic Events.

These models define the structure of events generated by the data generator
and ingested by the agent pipeline.
"""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EventType(str, Enum):
    """Event type classification."""
    PAYMENT_FAILED = "payment_failed"
    CHECKOUT_ABANDONED = "checkout_abandoned"
    MANDATE_FAILED = "mandate_failed"


class DeviceType(str, Enum):
    """Device type for checkout events."""
    MOBILE = "mobile"
    DESKTOP = "desktop"
    TABLET = "tablet"


class Channel(str, Enum):
    """Checkout channel."""
    WEB = "web"
    APP = "app"
    SOCIAL = "social"


class MandateType(str, Enum):
    """Mandate type for subscription events."""
    EMANDATE = "emandate"
    NACH = "nach"
    UPI_AUTOPAY = "upi_autopay"


class PaymentMethod(str, Enum):
    """Payment method."""
    CARD = "card"
    UPI = "upi"
    NETBANKING = "netbanking"
    WALLET = "wallet"


class Customer(BaseModel):
    """Customer details."""
    id: str
    email: str = ""
    phone: str = ""
    name: str = ""


class PaymentFailedEvent(BaseModel):
    """A failed payment event."""
    event_id: str
    event_type: EventType = EventType.PAYMENT_FAILED
    payment_id: str
    order_id: str = ""
    amount: float = Field(description="Amount in INR")
    currency: str = "INR"
    decline_reason: str = Field(description="Raw bank/gateway decline reason")
    decline_code: str = ""
    method: PaymentMethod = PaymentMethod.CARD
    bank: str = ""
    customer: Customer
    timestamp: datetime
    metadata: dict = Field(default_factory=dict)


class CheckoutAbandonedEvent(BaseModel):
    """An abandoned checkout event."""
    event_id: str
    event_type: EventType = EventType.CHECKOUT_ABANDONED
    order_id: str = ""
    cart_value: float = Field(description="Cart value in INR")
    currency: str = "INR"
    time_to_abandon_seconds: int = Field(description="Seconds from page load to abandonment")
    device_type: DeviceType = DeviceType.MOBILE
    channel: Channel = Channel.WEB
    items_count: int = 1
    customer: Customer
    timestamp: datetime
    metadata: dict = Field(default_factory=dict)


class MandateFailedEvent(BaseModel):
    """A failed subscription mandate event."""
    event_id: str
    event_type: EventType = EventType.MANDATE_FAILED
    subscription_id: str
    plan_id: str = ""
    amount: float = Field(description="Subscription amount in INR")
    currency: str = "INR"
    attempt_number: int = Field(description="Which attempt this failure is", ge=1)
    days_overdue: int = Field(description="Days past due date", ge=0)
    mandate_type: MandateType = MandateType.EMANDATE
    failure_reason: str = ""
    customer: Customer
    timestamp: datetime
    metadata: dict = Field(default_factory=dict)


class SyntheticBatch(BaseModel):
    """A batch of synthetic events with metadata."""
    batch_id: str
    generated_at: datetime
    seed: int
    total_events: int
    distribution: dict = Field(default_factory=dict)
    events: list[PaymentFailedEvent | CheckoutAbandonedEvent | MandateFailedEvent]
